name: SmartStash
description: A new Flutter project.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.14.0
  intl: ^0.19.0
  awesome_notifications: ^0.9.2
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git

flutter:
  uses-material-design: true
  assets:
    - lib/images/


dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  

